# Generated by Django 2.2.6 on 2020-03-11 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribuidor',
            name='nome',
        ),
    ]
