# Generated by Django 2.2.6 on 2020-03-14 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comprador', models.CharField(max_length=30)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Latitude')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Longitude')),
                ('tel_fixo', models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefone Fixo')),
                ('tel_celular', models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefone Celular')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cidade', models.CharField(blank=True, max_length=70, null=True, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, max_length=70, null=True, verbose_name='Bairro')),
                ('logradouro', models.CharField(blank=True, max_length=70, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=5, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=70, null=True, verbose_name='Complemento')),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Cadastro')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=30)),
                ('quantidade_em_estoque', models.IntegerField(blank=True, null=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comprador.Comprador')),
            ],
        ),
    ]
