# Generated by Django 2.2.6 on 2020-03-14 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidor', '0003_auto_20200310_2256'),
        ('comprador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qual_seu_pedido', models.CharField(max_length=30)),
                ('qual_quantidade_de_unidade', models.IntegerField()),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comprador.Comprador')),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='distribuidor.Distribuidor')),
            ],
        ),
    ]
