# Generated by Django 2.2.6 on 2020-03-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprador', '0002_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregue',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
