# Generated by Django 2.2.6 on 2020-03-16 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprador', '0003_auto_20200314_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='distribuidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='distribuidor.Distribuidor'),
        ),
    ]
