# Generated by Django 2.2.6 on 2020-03-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidor', '0002_remove_distribuidor_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribuidor',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Longitude'),
        ),
    ]
