# Generated by Django 2.2.6 on 2020-03-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuidor', '0004_auto_20200316_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuidor',
            name='fim_hora_entrega',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim Periodo Entrada'),
        ),
        migrations.AddField(
            model_name='distribuidor',
            name='inicio_hora_entrega',
            field=models.TimeField(blank=True, null=True, verbose_name='Inicio Periodo Entrada'),
        ),
    ]
